version: '3.8'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=YourStrong@Passw0rd
    networks:
      - backend-net

  sql-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    entrypoint: >
      bash -c "
      sleep 20 &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 'YourStrong@Passw0rd' -i /init/init.sql
      "
    volumes:
      - ./init:/init
    networks:
      - backend-net

  redis:
    image: "redis:7-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: .
    container_name: backend
    depends_on:
      redis:
        condition: service_healthy
      sqlserver:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=Gym;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - VN_PAY_URL=${VN_PAY_URL}
      - VN_PAY_TMN_CODE=${VN_PAY_TMN_CODE}
      - VN_PAY_SECRET_KEY=${VN_PAY_SECRET_KEY}
      - VN_PAY_RETURN_URL=${VN_PAY_RETURN_URL}
    ports:
      - "8000:8000"
    networks:
      - backend-net

networks:
  backend-net: